chore: update configs, paths and users to LeilFS
This commit updates the content of generated Debian packages by ensuring
new configuration files, paths and usernames are updated to new LeilFS
rebrand.

Signed-off-by: Rolando Sánchez Ramos <rolysr@leil.io>

diff --git a/debian/saunafs-common.postinst b/debian/saunafs-common.postinst
--- a/debian/saunafs-common.postinst
+++ b/debian/saunafs-common.postinst
@@ -2,22 +2,22 @@
 
 set -e
 
-sau_limits_conf="/etc/security/limits.d/10-saunafs.conf"
-sau_pam_d="/etc/pam.d/saunafs"
+leil_limits_conf="/etc/security/limits.d/10-leil.conf"
+leil_pam_d="/etc/pam.d/leil"
 
 case "${1}" in
 	configure)
-		if ! getent passwd saunafs > /dev/null 2>&1
+		if ! getent passwd leil > /dev/null 2>&1
 		then
-			adduser --quiet --system --group --no-create-home --home /var/lib/saunafs saunafs
+			adduser --quiet --system --group --no-create-home --home /var/lib/leil leil
 		fi
-		if [ ! -f $sau_limits_conf ]; then
-			echo "saunafs soft nofile 131072" > $sau_limits_conf
-			echo "saunafs hard nofile 131072" >> $sau_limits_conf
-			chmod 0644 $sau_limits_conf
+		if [ ! -f $leil_limits_conf ]; then
+			echo "leil soft nofile 131072" > $leil_limits_conf
+			echo "leil hard nofile 131072" >> $leil_limits_conf
+			chmod 0644 $leil_limits_conf
 		fi
-		if [ ! -f $sau_pam_d ]; then
-			echo "session	required	pam_limits.so" > $sau_pam_d
+		if [ ! -f $leil_pam_d ]; then
+			echo "session	required	pam_limits.so" > $leil_pam_d
 		fi
 		;;
 
@@ -33,17 +33,17 @@ esac
 
 # Ensure proper permissions on data dir and run dir.
 
-SAUNAFS_USER="saunafs"
-SAUNAFS_GROUP="saunafs"
-SAUNAFS_DATA_PATH="/var/lib/saunafs"
+LEIL_USER="leil"
+LEIL_GROUP="leil"
+LEIL_DATA_PATH="/var/lib/leil"
 
 check_dirs() {
 	# check that the metadata dir exists
-	if [ ! -d "$SAUNAFS_DATA_PATH" ]; then
-		mkdir -p "$SAUNAFS_DATA_PATH"
+	if [ ! -d "$LEIL_DATA_PATH" ]; then
+		mkdir -p "$LEIL_DATA_PATH"
 	fi
-	chmod 0755 "$SAUNAFS_DATA_PATH"
-	chown -R $SAUNAFS_USER:$SAUNAFS_GROUP "$SAUNAFS_DATA_PATH"
+	chmod 0755 "$LEIL_DATA_PATH"
+	chown -R $LEIL_USER:$LEIL_GROUP "$LEIL_DATA_PATH"
 }
 
 check_dirs
